### ISSUE TITLE
Beta-1: can't add 2nd athlete's info via wp-admin plugin settings, due to Strava error

### ISSUE THREAD

**Issue by lancewillett** [cmanon/wp-strava#8]
#### Steps to repeat

1. Update to https://github.com/cmanon/wp-strava/releases/tag/v1.2.0-beta1
2. Try to add another athlete with Additional Athlete Client ID and Additional Athlete Client Secret

#### What I expected to happen

To add another athlete, and be able to choose them from the widget "Athlete" list instead of "Default"

#### What actually happened

When I tried to add Carlos's info:

URI: https://www.strava.com/oauth/authorize?client_id=4920&response_type=code&redirect_uri=example.com/wp-admin/options-general.php?page=wp-strava-options&approval_prompt=force

<img width="768" alt="screen shot 2017-10-26 at 11 19 37" src="https://user-images.githubusercontent.com/66797/32070001-bc6903bc-ba3f-11e7-9a00-b13a844b2844.png">

Error:
```
{"message":"Bad Request","errors":[{"resource":"Application","field":"redirect_uri","code":"invalid"}]}
```

**Comment by jrfoell** [comment]
So for testing a 2nd athlete we can't just share the client ID & secret because the Strava API does the authorization based on domain as well :(

What I did to test was create a 2nd (and 3rd) strava accounts just for testing using an alternate email. If you have a friend that has a strava account and is willing to authenticate theirs, that would work too.

I'll leave this open, especially if you guys have any suggestions the wording or formatting of the connection process so this is clear to everyone.
